# The configuration schema is defined by service.proto file
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

# Name of the service configuration.
name: hellogrpc-endpoint-ekwl7yofpq-ue.a.run.app

# API title to appear in the user interface (Google Cloud Console).
title: Hello gRPC API
apis:
  - name: helloworld.Greeter
usage:
  rules:
    - selector: helloworld.Greeter.SayHello
      allow_unregistered_calls: true
backend:
  rules:
    - selector: "*"
      address: grpcs://hellogrpc-ekwl7yofpq-ue.a.run.app